on:
  push: {}

jobs:
  example_matrix:
    strategy:
      matrix:
        # os: [ubuntu-22.04, ubuntu-20.04]
        version:
          - v0.17.0
          - v0.16.0
          - v0.15.0
          - v0.14.0
          - v0.13.0
          - v0.12.0
          - v0.11.0
          - v0.10.0
          - v0.9.0
          - v0.8.0
        pgversion:
          - 15.1-bullseye
          - 14.6-bullseye
          - 13.9-bullseye
          - 12.13-bullseye
          - 11.18-bullseye
          - 10.23-bullseye
          - 9.6-bullseye
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta first
        id: first
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/first
          tags: |
            ${{ matrix.version }}-${{ matrix.pgversion }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker build & push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.first.outputs.tags }}
          labels: ${{ steps.first.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7
          network: host
          build-args: |
            PGVERSION=${{ matrix.pgversion }}
            VERSION=${{ matrix.version }}
